# Generated by Django 4.1 on 2022-09-10 12:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MhTotalDist",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("layer", models.CharField(blank=True, max_length=17, null=True)),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "perimeter",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                ("indiadpoly", models.FloatField(blank=True, null=True)),
                ("indiadpo_1", models.FloatField(blank=True, null=True)),
                ("dist", models.CharField(blank=True, max_length=254, null=True)),
                ("cnt_dist", models.FloatField(blank=True, null=True)),
                (
                    "sum_area",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("symbol", models.IntegerField(blank=True, null=True)),
                (
                    "shape_leng",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "shape_area",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                ("area_1", models.IntegerField(blank=True, null=True)),
                ("area_12", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=0
                    ),
                ),
            ],
            options={
                "db_table": "mh_total_dist",
                "managed": False,
            },
        ),
    ]
